# Generated by Django 3.2 on 2023-06-05 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='creator',
            field=models.CharField(blank=True, max_length=256, verbose_name='候选人数据的创建人'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='优势'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='顾虑和不足'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_interviewer',
            field=models.CharField(blank=True, max_length=256, verbose_name='面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_recommend_position',
            field=models.CharField(blank=True, max_length=256, verbose_name='推荐部门'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_remark',
            field=models.CharField(blank=True, max_length=135, verbose_name='初试备注'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_result',
            field=models.CharField(blank=True, choices=[('建议复试', '建议复试'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='初试结果'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='物试分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='优势'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_communication_ability',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR坦诚沟通门'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='顾虑和不足'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_interviewer',
            field=models.CharField(blank=True, max_length=256, verbose_name='HR面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_logic_ability',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR逻辑思维'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_potential',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR发展潜力'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_remark',
            field=models.CharField(blank=True, max_length=256, verbose_name='HR复试备注'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_responsibility',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR贵任心'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_result',
            field=models.CharField(blank=True, choices=[('建议录用', '建议录用'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='HR复试结果'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_score',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR复试综合等级'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_stability',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR稳定性'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_editor',
            field=models.CharField(blank=True, max_length=256, verbose_name='最后编辑者'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='paper_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='笔试成绩'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='优势'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_communication_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='沟通能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='顾虑和不足'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_interviewer',
            field=models.CharField(blank=True, max_length=256, verbose_name='面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_pressure_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='抗压能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_pursue_of_excellence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='追求卓越得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_recommend_position',
            field=models.CharField(blank=True, max_length=256, verbose_name='建议方向或推荐部门'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_remark',
            field=models.CharField(blank=True, max_length=135, verbose_name='专业复试备注'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_result',
            field=models.CharField(blank=True, choices=[('建议录用', '建议录用'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='专业复试结果'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业复试得分'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='test_score_of_general_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合能力测评成绩'),
        ),
    ]
