# Generated by Django 3.2 on 2023-06-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20230605_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='candidate',
        ),
    ]
